alias start="DISPLAY=:0 terminator &"
alias ls="colorls --sd"
alias lc="colorls"
source $(dirname $(gem which colorls))/tab_complete.sh
alias cat="bat"
alias cmd="cmd.exe /c"
alias npm="cmd.exe /c npm"
alias node="cmd.exe /c node"
alias yarn="cmd.exe /c yarn"
alias nvm="cmd.exe /c nvm"
alias killnode="cmd taskkill -F -IM node.exe"
alias killzsh="ps -aux | grep zsh"
alias housekeeper="/usr/bin/node /home/jeyson/workspace/housekeeper/main.js"
alias explorer="cmd.exe /c start ."
alias nvim="/home/jeyson/nvim-0.4/usr/bin/nvim"
